import { useMemo } from "react";

function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function resolveBlueprintData(response, blueprint) {
  const candidates = [blueprint, response?.blueprint, response?.data?.blueprint, response?.data, response?.result?.blueprint, response?.result, response];
  return candidates.find((entry) => isPlainObject(entry)) || {};
}

function normalizeText(value, fallback = "Not provided") {
  if (typeof value === "string" && value.trim()) return value.trim();
  return fallback;
}

function stringifySection(value) {
  if (Array.isArray(value)) return value.map((item) => (typeof item === "string" ? item : JSON.stringify(item))).join(" • ");
  if (isPlainObject(value)) return Object.entries(value).map(([k, v]) => `${k.replace(/_/g, " ")}: ${typeof v === "string" ? v : JSON.stringify(v)}`).join(" • ");
  return normalizeText(value, "Not available");
}

function StarterBlueprintResult({ response, blueprint, intakeValues, onUpgradePro, onSeeElite, onStartAnother }) {
  const blueprintData = useMemo(() => resolveBlueprintData(response, blueprint), [response, blueprint]);
  const blueprintText = typeof response?.blueprintText === "string" ? response.blueprintText : "";

  const accessLevel = (intakeValues?.accessLevel || intakeValues?.accessTier || "free").toLowerCase();
  const businessName = normalizeText(intakeValues?.proposedBusinessName, normalizeText(blueprintData?.business_snapshot?.business_name, "your business"));
  const domain = normalizeText(intakeValues?.domainToCheck, normalizeText(blueprintData?.businessIdentity?.domainToCheck, "Not selected"));

  const cards = [
    { title: "Business summary", value: stringifySection(blueprintData.business_snapshot || blueprintData.ventureSummary) },
    { title: "Target customer", value: normalizeText(blueprintData?.business_snapshot?.target_customer || intakeValues?.targetCustomer) },
    { title: "Offer", value: normalizeText(blueprintData?.business_snapshot?.basic_offer_idea || blueprintData?.business_snapshot?.product_or_service || intakeValues?.productOrService) },
    { title: "Domain / brand foundation", value: `Business name: ${businessName} • Domain: ${domain}` },
    { title: "Startup checklist", value: stringifySection(blueprintData.startup_requirements || blueprintData.launch_plan_30_days) },
    { title: "Next steps", value: stringifySection(blueprintData.launch_plan_30_days || blueprintData.operations_plan_90_days) },
  ];
  const hasStructuredBlueprint = Object.keys(blueprintData || {}).length > 0;

  return (
    <div className="starter-result starter-reveal">
      <header className="starter-result__header">
        <p className="starter-result__eyebrow">PEN2PRO BLUEPRINT</p>
        <h2 className="starter-result__title">{businessName}</h2>
        <p className="starter-result__subtitle">Generated by PEN2PRO</p>
        <p className="starter-result__meta">Domain: {domain}</p>
      </header>

      <section className="starter-result__bento">
        {cards.map((card, idx) => (
          <article key={card.title} className={`starter-result__bento-card starter-result__bento-card--${(idx % 3) + 1}`}>
            <h3>{card.title}</h3>
            <p>{card.value}</p>
          </article>
        ))}
        {!hasStructuredBlueprint && (
          <article className="starter-result__bento-card starter-result__bento-card--1">
            <h3>Generated blueprint</h3>
            <p>{blueprintText || "Blueprint generated, but no blueprint text was returned."}</p>
          </article>
        )}
      </section>

      {accessLevel === "free" && (
        <section className="starter-upsell starter-upsell--locked">
          <h3>Unlock Full Strategist Modes</h3>
          <p>Pro and Elite unlock deeper strategist breakdowns for branding, monetization, marketing, operations, and legal/foundation planning.</p>
          <div className="starter-result__cta-actions">
            <button className="starter-button starter-button--primary" onClick={onUpgradePro}>Upgrade to Pro</button>
            <button className="starter-button starter-button--primary" onClick={onSeeElite}>Unlock Elite 10M Strategist</button>
          </div>
        </section>
      )}

      {accessLevel === "pro" && (
        <section className="starter-upsell starter-upsell--elite">
          <h3>Unlock Elite 10M Strategy</h3>
          <p>Elite adds advanced projections, automation opportunities, scaling milestones, and a founder-level 10M roadmap.</p>
          <div className="starter-result__cta-actions">
            <button className="starter-button starter-button--primary" onClick={onSeeElite}>Upgrade to Elite</button>
          </div>
        </section>
      )}

      <section className="starter-result__cta-block">
        <div className="starter-result__cta-actions">
          {typeof onStartAnother === "function" && (
            <button className="starter-button starter-button--secondary" onClick={onStartAnother}>Start Another Blueprint</button>
          )}
        </div>
      </section>
    </div>
  );
}

export default StarterBlueprintResult;
